# Generated by Django 3.2.12 on 2022-04-06 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=300)),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
    ]
